{% set name = "parse-fmt" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/parse-fmt-{{ version }}.tar.gz
  sha256: 6cfdc4b9a4e00e7e11438b54ac56aeadd433b4b9ab898f03e33b43f522a7c4bc

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - parsefmt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/CCP-NC/parse-fmt
  summary: A Python parser for CASTEP fmt files (densities, potentials etc.)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stur86
